user  root;
worker_processes  1;

pid        /var/run/nginx.pid;


events {
  worker_connections  10240;
  accept_mutex off;
}

env HQCLOUD_POD_NAME;

http {
  server_tokens off;
  include       mime.types;
  default_type  application/octet-stream;

  log_format nginx_logs  '{ "timeLocal": "$time_local", '
                           '"traceId":"$traceId",'
                           '"serviceTag":"gt-article-test-nginx",'
                           '"lastServiceTag":"$http_last_service_tag",'
                           '"msgId":"$messageId",'
                           '"pMsgId":"$http_parent_message_id",'
                           '"userIp": "$remote_addr", '
                           '"realIp": "$http_x_gt_ip", '
                           '"referer": "$http_referer", '
                           '"cookieId":"$cookie_cu_uba",'
                           '"req": "$request", '
                           '"host":"$http_host", '
                           '"uri":"$uri", '
                           '"serverAddr":"$server_addr",'
                           '"port":$server_port,'
                           '"status": $status, '
                           '"bytes": $body_bytes_sent, '
                           '"agent": "$http_user_agent", '
                           '"upAddr": "$upstream_addr",'
                           '"upHost": "$upstream_http_host",'
                           '"upDuration": "$upstream_response_time",'
                           '"duration": "$request_time"'
                         ' }';

  access_log  /var/app/logs/nginx/logs_access_${yearmonthday}_$server_addr.log nginx_logs;
  error_log /var/app/logs/nginx/logs_error-gtwork-nginx.log;

  server{

    listen       80;
    server_name  yundoc.gt.cn;
    underscores_in_headers on;

    set_by_lua $serviceTag '
      local pod_name = os.getenv("HQCLOUD_POD_NAME")
      return "gt-work-portal-test-nginx"
    ';

    set_by_lua $userIp '
      return ngx.var.http_x_gt_ip or ngx.var.remote_addr
    ';

    set $traceId $http_traceid;
    if ($traceId = '') {
    set_by_lua $traceId '
      local realIp = ngx.var.http_x_gt_ip or ngx.var.remote_addr
      local rndCode = math.random(1000000000, os.time())
      local x = ngx.var.msec..realIp..ngx.var.host..ngx.var.server_port..(ngx.now()*1000)..ngx.var.uri..rndCode
      return ngx.md5(x)
    ';
    }

    set_by_lua $messageId '
      local realIp = ngx.var.http_x_gt_ip or ngx.var.remote_addr
      local rndCode = math.random(1000000000, os.time())
      local x = ngx.var.msec..realIp..ngx.var.host..ngx.var.server_port..(ngx.now()*1000)..ngx.var.uri..rndCode
      return ngx.md5(x)
    ';

    set $yearmonthday "";
    set_by_lua $yearmonthday '
      return ngx.today()
    ';
    location /netstat {
      content_by_lua '
        ngx.header.content_type = "application/json";
        local lastServiceTag = ngx.var.http_last_service_tag;
        if(not lastServiceTag )
        then
          lastServiceTag = "slb-test";
        end
        local ret = [[{"slb": "]]..lastServiceTag..[["}]];
        ngx.say(ret);
      ';
    }
    set $agent $http_user_agent;
    set $mobile $http_sec_ch_ua_mobile;
    set $platform $http_sec_ch_ua_platform;
    location /doc_center {
        client_max_body_size 200m;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_pass   http://doc-center-api:8080/doc_center;
    }
    location /sms-billing/ {
      add_header Cache-Control no-cache;
      alias /usr/share/nginx/html/;
      index index.html;
    }

  }
}
