app:
  id: sms-billing
apollo:
  meta: http://10.155.72.55:61112,http://10.155.72.56:61112,http://10.155.72.57:61112
  bootstrap:
    namespaces: sms-billing.yaml
    enabled: true
    eagerLoad:
      enabled: true